### ISSUE TITLE
Error parsing twig template

### ISSUE THREAD

**Issue by iGitScor** [zimmen/gulp-twig#13]
I'm having an issue with using filter and compiling my twig.

I got the follwoing error :
```sh
Error parsing twig template /home/[...]/Documents/dev/[...]/sources/plain/views/index.twig: 
Unable to find filter trans
```

The problem is here :
```twig
{{ 'amazing' | trans() }}
```

Here my gulp task :
```js
gulp.src(source.split(','))
        .pipe($.data(function () {
          var content = {};
          if (config.content !== 'no') {
            var contentPath = path.join(process.cwd(), config.contentPath);
            fs.readdirSync(contentPath).forEach(function (file) {
              var filePath = path.join(contentPath, file);
              if (path.extname(file) === '.json') {
                // No cache for template content
                delete require.cache[require.resolve(filePath)];
                content = _.merge(content, require(filePath));
              }
            });
          }
          return content;
        }))
        .pipe($.twig({
          filters: [
            {
              name: "trans",
              func: function (args) {
                return "the function";
              }
            }
          ]
        }))
        .pipe(gulp.dest(dist));
```

I'm trying to reproduce Symfony2 behavior

**Comment by mowcixo** [comment]
That's because, the trans() function its a Symfony2 extension over Twig... you can see all the Twig.js supported functionality at https://github.com/justjohn/twig.js/wiki/Implementation-Notes

By the way... in your code, if you change the "filters" key, by "functions", it could work.

**Comment by iGitScor** [comment]
I know trans is a Symfony2 extension.
Even if I change trans as a function, I get the same mesage (`` Unable to find filter trans ``)

**Comment by mowcixo** [comment]
What version are you using in your package.json?, there is no tag for the "filters" support... so you have to use:

    "gulp-twig": "*"

Another thing... the $.twig var is equals to: require('gulp-twig') I suppose.

**Comment by iGitScor** [comment]
In my package.json : `` "gulp-twig": "^0.3.0" ``

Yes, `` $.twig = require('gulp-twig') ``

**Comment by mowcixo** [comment]
That's because of the tag in the repo or in npm... maybe @zimmen can handle this.

**Comment by zimmen** [comment]
Hi @iGitScor , You can update the package.json to `"gulp-twig":"^0.4.0"` ( or `"gulp-twig":"*"` although this could bring in breaking changes some day )

Thanks for the heads-up @mowcixo

**Comment by mowcixo** [comment]
With this changes it could work @iGitScor. Thanks @zimmen.

**Comment by iGitScor** [comment]
Yes, it works ! Thanks
