### ISSUE TITLE
Use with atpl.js

### ISSUE THREAD

**Issue by TxHawks** [zimmen/gulp-twig#16]
I saw `atpl.js` mentioned in the readme, but Is it currently possible to use this plugin with atpl.js?

**Comment by olets** [comment]
@TxHawks did you ever get anywhere using `gulp-twig` and `atpl.js`? And do you think it's worth keeping this ticket open?

**Comment by dotmagic** [comment]
I think we should remove atpl from the readme, it's confusing. I don't think it make sense to support twig.js and atpl.

**Comment by TxHawks** [comment]
I never got anything with it, and twig.js is at a much better stage today

**Comment by olets** [comment]
Closed by ba65708
