### ISSUE TITLE
Unable to parse 'verbatim'

### ISSUE THREAD

**Issue by LoicGoyet** [zimmen/gulp-twig#17]
Hello, I'm trying to use the [verbatim tag](http://twig.sensiolabs.org/doc/tags/verbatim.html) in the simpliest way possible :
```
{% verbatim %}
    hello world
{% endverbatim %}
```

the terminal can not compile it and output this :
```
TwigException: Unable to parse 'verbatim'
```

But it seems that twig.js does support the tag. How could I use the feature ? Do I must switch it on ? Is it not supported ?

Thanks ;)

**Comment by zimmen** [comment]
Hi @LoicGoyet . Twig.js doesnt have a release note so it took some digging but it looks like the verbatim tag came into their code trough some PR in version 0.8.3 ... gulp-twig is on 0.8.2 still :-)

I'll update the twig dependency, in the meantime you could use the old {%raw%} {%endraw%} tags

**Comment by tremby** [comment]
@zimmen, please do update the dependency -- there are some other nice new features since 0.8.2.

**Comment by zimmen** [comment]
Updated. Sorry for the delay!
