### ISSUE TITLE
Don't output extended templates

### ISSUE THREAD

**Issue by stevieg83** [zimmen/gulp-twig#20]
Is there a way just to stop that output and just output the templates that extend the base?

**Comment by zimmen** [comment]
Not sure what you mean... you would like to output the compiled twig without whatever it extends? Simply not extending those templates isn't an option?

What is the usecase?

**Comment by stevieg83** [comment]
For example, I have index.twig that extends layout.twig and when it compiles, I get index.html and layout.html -- layout.html doesn't actually serve any purpose. We're only ever interested in index.html if that makes sense?

**Comment by zimmen** [comment]
Ah yes, well, it looks like you are compiling the layout twig file as well. You could solve this in a lot of ways but it comes down to making sure those files aren't included in the gulp.src.

You could create a folder structure where pages and base layouts are on the same level and run gulp-twig on the folder containing the pages. You could also prefix files that are for extending and including with '_' and exclude them in gulp.src

**Comment by stevieg83** [comment]
Gotcha. I normally do _layout.twig but I saw that was compiling too, didn't realise I'd need to manually exclude them.

This worked just nicely in my Gulp config file

```
twig: {
    src: templates + '/**/[^_]*.twig',
    dest: dest
  },
```

**Comment by zimmen** [comment]
Great, that's kind of like how I do this as well :-)

**Comment by stevieg83** [comment]
Also, thank you for this.

Love Twig but everything else for integration was too heavy for simply DRY
writing markup.

Now a simple Gulp task and we're golden.

On 1 December 2015 at 17:03, Simon <notifications@github.com> wrote:

> Great, that's kind of like how I do this as well :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zimmen/gulp-twig/issues/20#issuecomment-161032935>.
>



-- 
Steven Grant
