### ISSUE TITLE
Linebreaks inside "with" params will cause an exception

### ISSUE THREAD

**Issue by bluemoehre** [zimmen/gulp-twig#28]
I noticed line breaks inside the parameters object will break the embed function.

Will work:

``` twig
{% embed 'skeletons/sidebarBox.twig' with { 'class': 'relatedContents' } %}
…
{% endembed %}
```

Won't work:

``` twig
{% embed 'skeletons/sidebarBox.twig' with {
    'class': 'relatedContents'
} %}
…
{% endembed %}
```

> TwigException: Unable to parse 'embed 'skeletons/sidebarBox.twig' with {
>     'class': 'relatedContents'
> }'

This behavior is different to `include` and `require` where line breaks cause no trouble.

**Comment by dotmagic** [comment]
This is just the gulp plugin. The bug is in twig.js, it seems to be fixed already.
https://github.com/twigjs/twig.js/issues/386

I suggest to close this issue.
