### ISSUE TITLE
Pipe modified templates by passing file.contents into twigOpts.data

### ISSUE THREAD

**Issue by signal-intrusion** [zimmen/gulp-twig#30]
This gulp task does not allow us to pipe in files where we have changed the template in a previous gulp task. For example, we have templates with front matter that we remove (check out the example in the gulp-data repo), but the front matter is still rendered.

Passing the file contents as the data property to twigOpts. `twig.js` will use the string in `file.data` when you call `Twig.twig(twigOpts)`. Check out the `twig.js` source where it renders a template from `params.data`: https://github.com/twigjs/twig.js/blob/master/src/twig.exports.js#L41-L48

This would allow gulp tasks to, in effect, change templates before rendering them. _It would also speed up rendering because it will use buffered data, avoiding an expensive call to `Twig.loadRemoteContent()` fetching templates from the filesystem._

```
      var Twig = require('twig'),
            twig = Twig.twig,
            twigOpts = {
                path: file.path,
                async: false
            },
            template;

        if (!!useFileContents) {
            twigOpts.data = String(file.contents);
        }
```

**Comment by bezoerb** [comment]
https://github.com/zimmen/gulp-twig/releases/tag/v1.2.0
