### ISSUE TITLE
How to exclude files?

### ISSUE THREAD

**Issue by MickL** [zimmen/gulp-twig#33]
I want to use twig.js for css-templating. My structure is something like:

html.twig
header.twig
footer.twig

mainpage.twig
customers.twig
contact.twig

The first 3 are only partials and i dont want them to get compiled which does `gulp.src('./template/**/*.twig')`. Is there any easy way to do this? Ofcourse i could put them into a seperate folder. But for example on sass if you name a file with a "_" prefix they wont get compiled. (e.g. _html.twig).

**Comment by dotmagic** [comment]
@MickL This question is not gulp-twig.js related. You can use `gulp.src('./template/**/[^_]*.twig')` and prefix your partials with underscore. However, I prefer to have then in a separate folder.

**Comment by davidhellmann** [comment]
Hm but the problem is browserSync does not refresh with the `[^_]` "hack". Partial support would be nice.

**Comment by dotmagic** [comment]
@davidhellmann I don't see the problem? You ignore all `_` prefixed templates with for rendering. browser-sync is a separate task in my setup, it runs parallel and watch all files changes.

**Comment by olets** [comment]
`**/[^_]*.twig` isn't a hack, it's a glob that matches all files in `./template` (at any depth) that don't start with an underscore.

You can also exclude explicitly with: `gulp.src('yes1', 'yes2', '!no1, '!no2')`

Check out [Gulp for Beginners: Globbing in Node](https://css-tricks.com/gulp-for-beginners/#article-header-id-7) and isaacs' [Glob Primer](https://github.com/isaacs/node-glob#glob-primer). You can test patterns with [Glob online tester](https://codepen.io/mrmlnc/full/OXQjrZ)
