### ISSUE TITLE
‘set’ variable causes a bug

### ISSUE THREAD

**Issue by icai** [zimmen/gulp-twig#39]
` {% set bodyCls = 'sss' %} `

If have a template set this, all template render the ClassName while all template extends the same layout

**Comment by olets** [comment]
I don't completely understand. Can you post example code, or make a https://twigfiddle.com/ to demo the problem?

**Comment by icai** [comment]
@olets  If have a template set this, all template render the same ClassName while all template `extends` the same layout, I also the  `option.extend` (`Twig.extend` ) to rewite the `Twig.token.definitions`

**Comment by icai** [comment]
@example 

**index.page**

---

{% extends 'layout.html' %}

{% set bodyCls = 'fixed-sidebar full-height-layout gray-bg skin-1' %}

{% block style %}

{% endblock %}

{% block body %}
{% endblock %}

---

**other.page**

i never set the bodyCls, but this page also have the bodyCls like the `index.page`

{% extends 'layout.html' %}

{% block style %}

{% endblock %}

{% block body %}
{% endblock %}

**Comment by icai** [comment]
@olets 
here is the task code
>     var twig = require('gulp-twig');
>     return gulp.src(['./views/**/*.html', '!./views/error.html', '!./views/layout.html'])
>         .pipe(twig({
>             extend: function(Twig) {
>                 require('./config/twig')(Twig);
>                 // twigConfig(Twig);
>             },
>             base: './views/',
>             data: {
>                 // title: 'Express'
>             }
>         }))
>         .pipe(gulp.dest(opt.tmp));

**Comment by olets** [comment]
Don't know what your `layout.twig` is like, so guessing a little here. Are you saying this?

For

```twig
{# main.twig #}

{% extends 'extended.twig' %}
```
```twig
{# other.twig #}

{% extends 'extended.twig' %}
{% set x = 1 %}
```
```twig
{# extended.twig #}
{{ x }}
```

`main.twig` compiles to
```
1
```

I tried that with the latest gulp-twig, and `main.twig` is compiling as empty.

@icai can you make a minimal example that reproduces your problem? I wonder if the problem might be something in your templates or your `./config/twig`

**Comment by icai** [comment]
https://github.com/zimmen/gulp-twig/issues/44

**Comment by olets** [comment]
Are you saying #44 replaces this issue? If so, go ahead and close this one
