### ISSUE TITLE
bringing releases up to date

### ISSUE THREAD

**Issue by olets** [zimmen/gulp-twig#42]
Following up on the discussion at #32 

> bezoerb wrote
> olets, dotmagic, webrgp: i think we should consider #18, #19 and #21 before v1.0.0 release. What do you think?

> olets wrote
> I think go with 1.0.0 now. For me, dependencies like this should follow semver - so bumping from 0.x to 1.0 is saying "there was a breaking change" not "we've ironed out the bugs." The upgraded node requirement is a breaking change.
>
> If we do use a lower version, we'll have to remember to downgrade the version in package.json from the bump in f64df15

8aea9c2 bumped the package.json, but a new release was never tagged. Since there was no push-back I imagine 1.0.0 at 8aea9c2 is acceptable. Otherwise we'll need to back down from 1.0.0 in package.json (which would be funny, since 8aea9c2 and the related changes in Twig.js are all about not dropping below 1.0.0 😉  - it's the lowest at which semver ranges work in npm)

I additionally propose bumping master to and releasing 1.1, so that npm users have access to #19.

**Comment by bezoerb** [comment]
@olets thanks for bringing that up again ;)
Why shouldn't we just release the v1.0.0 now?

**Comment by bezoerb** [comment]
Released. Just need you to merge https://github.com/zimmen/gulp-twig/pull/43

**Comment by dotmagic** [comment]
I would like to see updated twigjs, v1.10.5 was already released when we upgrade to v1.10.4. And readme.md cleanup (remove atpl reference) before we're going to bump the version again.

**Comment by bezoerb** [comment]
v1.10.5 is already catched by `"^1.10.4"`

**Comment by bezoerb** [comment]
I've changed it anyway

**Comment by olets** [comment]
Fyi best to tag the upstream repo only after merge - `0575656` has been the default `npm install gulp-twig` point since the tag was added.

Yep no reason to bump the Twig.js dependency until it hits v2. Just introduces noise

@bezoerb Ha you are quick! Leaving some feedback in the PR

@dotmagic what versioning scheme do you picture for this project? I'd like to use semver: `breakingchanges.newfeatures.fixes`. That will lead to more frequent releases, but that's good: updates will ship to npm much more quickly. No matter what, it could be good to formalize

**Comment by dotmagic** [comment]
@olets I prefer semver too. Sadly twigjs doesn't follow semver and releases had often breaking changes in the past. However, small backwards compatible tweaks, cleanups like the one I've mention above can always be applied. I don't think it's against semver.

**Comment by olets** [comment]
@dotmagic makes sense. Hoping to get Twig.js on a more semver release schedule, we'll see how that goes
